export { CharNameModal } from "./character/inputs/name-input";
export { SpeciesModal } from "./character/inputs/species-input";
export { GenderOptions } from "./character/lists/gender-list";
export { StatusOptions } from "./character/lists/status-list";
export { NameOption } from "./character/options/name-option";
export { SpeciesOption } from "./character/options/species-option";
export { EpisodeModal } from "./episode/inputs/episode-input";
export { EpisodeNameModal } from "./episode/inputs/name-input";
export { EpisodeOption } from "./episode/options/episode-option";
export { NameOption as EpisodeNameOption} from "./episode/options/name-option";
export { NameModal } from "./location/inputs/name-input";
export { LocDimensionOption } from "./location/options/dimension-option";
export { LocNameOption } from "./location/options/name-option";
export { LocTypeOption } from "./location/options/type-option";
export { DimensionModal } from "./location/inputs/dimension-input";
export { TypeModal } from "./location/inputs/type-input";
